function Dessiner(context){
	this.ctx=context;
	this.joueur=function(player){
		context.beginPath();
		context.fillStyle="rgb(0,0,255)";
		context.fillRect(player.x,player.y,20,20);
		context.closePath();
	}
	this.block=function(block,x,y){
		context.beginPath();
		if(block.unbreakable){
			context.fillStyle="rgb(0,0,0)";
		}
		else{
			context.fillStyle="rgb(255,255,255)";
		}
		context.fillRect(x*20,y*20,20,20);
		context.closePath();
	}
	this.vide=function(cellule){
		context.beginPath();
		context.fillStyle="rgb(51,153,0)";
		context.fillRect(cellule.x*20,cellule.y*20,20,20);
		context.closePath();
	}
	this.bombe=function(bombe){
		context.beginPath();
		context.fillStyle="rgb(204,0,0)";
		context.fillRect(bombe.x*20,bombe.y*20,20,20);
		context.closePath();
	}
}